<!DOCTYPE dataset [ 
	<!ELEMENT dataset (table*)>
	<!ELEMENT table (column*, row*)>
	<!ATTLIST table
	    name CDATA #REQUIRED
	>
	<!ELEMENT column (#PCDATA)>
	<!ELEMENT row (value | null | none)*>
	<!ELEMENT value (#PCDATA)>
	<!ELEMENT null EMPTY>
]>

<dataset>
    <table name="users">
    	<column>id</column>
        <column>email</column>
        <column>username</column>
        <column>password</column>
        <column>enabled</column>
        <column>account_expired</column>
        <column>account_locked</column>
        <column>credentials_expired</column>
        <column>version</column>
        <row>
        	<value>1</value>
            <value>khim@gmail.com</value>
            <value>khim@gmail.com</value>
            <value>$2a$10$g9ciTLcpCML0EMiNXW7.WOGrtakszt9H56N6CQXiQB7tmbNU5uWdu</value>
            <value>1</value>
            <value>0</value>
            <value>0</value>
            <value>0</value>
            <value>0</value>
        </row>
        <row>
            <value>2</value>
            <value>khim1@gmail.com</value>
            <value>$2a$10$g9ciTLcpCML0EMiNXW7.WOGrtakszt9H56N6CQXiQB7tmbNU5uWdu</value>
            <value>1</value>
            <value>0</value>
            <value>0</value>
            <value>0</value>
            <value>0</value>
        </row>
    </table>
    <table name="role">
        <column>id</column>
        <column>name</column>
        <row>
            <value>1</value>
            <value>USER_ROLE</value>
        </row>
        <row>
            <value>2</value>
            <value>ADMIN_ROLE</value>
        </row>        
    </table>
    <table name='user_role'>
        <column>user_id</column>
        <column>role_id</column>
        <row>
            <value>1</value>
            <value>1</value>
        </row>   
        <row>
            <value>2</value>
            <value>2</value>
        </row>           
    </table>
</dataset>
